### ISSUE TITLE
How to train kitti dataset on imvotenet model?

### ISSUE THREAD

**Issue by daxiongpro** [kathy-lee/mmdet3d-nd#1]
I want to ask how to write config file for train `kitti `dataset on `imvotenet`. I find the default dataset is sun-rgbd dataset on imvotenet

**Comment by daxiongpro** [comment]
this is my imvotenet with kitti dataset, but it occurs an error.

    _base_ = [
        '../_base_/datasets/kitti-3d-3class.py',
        '../_base_/schedules/schedule_3x.py', '../_base_/default_runtime.py',
        '../_base_/models/imvotenet_image.py'
    ]
    
    
    # dataset settings
    dataset_type = 'KittiDataset'
    data_root = 'data/kitti/'
    class_names = ['Pedestrian', 'Cyclist', 'Car']
    input_modality = dict(use_lidar=True, use_camera=True)
    db_sampler = dict(
        data_root=data_root,
        info_path=data_root + 'kitti_dbinfos_train.pkl',
        rate=1.0,
        prepare=dict(
            filter_by_difficulty=[-1],
            filter_by_min_points=dict(Car=5, Pedestrian=5, Cyclist=5)),
        classes=class_names,
        sample_groups=dict(Car=20, Pedestrian=15, Cyclist=15))
    
    
    # use caffe img_norm
    img_norm_cfg = dict(
        mean=[103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0], to_rgb=False)
    
    model = dict(
        pts_backbone=dict(
            type='PointNet2SASSG',
            in_channels=4,
            num_points=(2048, 1024, 512, 256),
            radius=(0.2, 0.4, 0.8, 1.2),
            num_samples=(64, 32, 16, 16),
            sa_channels=((64, 64, 128), (128, 128, 256), (128, 128, 256),
                         (128, 128, 256)),
            fp_channels=((256, 256), (256, 256)),
            norm_cfg=dict(type='BN2d'),
            sa_cfg=dict(
                type='PointSAModule',
                pool_mod='max',
                use_xyz=True,
                normalize_xyz=True)),
        pts_bbox_heads=dict(
            common=dict(
                type='VoteHead',
                num_classes=3,
                bbox_coder=dict(
                    type='PartialBinBasedBBoxCoder',
                    num_sizes=3,
                    num_dir_bins=12,
                    with_rot=True,
                    mean_sizes=[[2.114256, 1.620300, 0.927272],
                                [0.791118, 1.279516, 0.718182],
                                [0.923508, 1.867419, 0.845495],
                                ]),
                pred_layer_cfg=dict(
                    in_channels=128, shared_conv_channels=(128, 128), bias=True),
                conv_cfg=dict(type='Conv1d'),
                norm_cfg=dict(type='BN1d'),
                objectness_loss=dict(
                    type='CrossEntropyLoss',
                    class_weight=[0.2, 0.8],
                    reduction='sum',
                    loss_weight=5.0),
                center_loss=dict(
                    type='ChamferDistance',
                    mode='l2',
                    reduction='sum',
                    loss_src_weight=10.0,
                    loss_dst_weight=10.0),
                dir_class_loss=dict(
                    type='CrossEntropyLoss', reduction='sum', loss_weight=1.0),
                dir_res_loss=dict(
                    type='SmoothL1Loss', reduction='sum', loss_weight=10.0),
                size_class_loss=dict(
                    type='CrossEntropyLoss', reduction='sum', loss_weight=1.0),
                size_res_loss=dict(
                    type='SmoothL1Loss', reduction='sum', loss_weight=10.0 / 3.0),
                semantic_loss=dict(
                    type='CrossEntropyLoss', reduction='sum', loss_weight=1.0)),
            joint=dict(
                vote_module_cfg=dict(
                    in_channels=512,
                    vote_per_seed=1,
                    gt_per_seed=3,
                    conv_channels=(512, 256),
                    conv_cfg=dict(type='Conv1d'),
                    norm_cfg=dict(type='BN1d'),
                    norm_feats=True,
                    vote_loss=dict(
                        type='ChamferDistance',
                        mode='l1',
                        reduction='none',
                        loss_dst_weight=10.0)),
                vote_aggregation_cfg=dict(
                    type='PointSAModule',
                    num_point=256,
                    radius=0.3,
                    num_sample=16,
                    mlp_channels=[512, 128, 128, 128],
                    use_xyz=True,
                    normalize_xyz=True)),
            pts=dict(
                vote_module_cfg=dict(
                    in_channels=256,
                    vote_per_seed=1,
                    gt_per_seed=3,
                    conv_channels=(256, 256),
                    conv_cfg=dict(type='Conv1d'),
                    norm_cfg=dict(type='BN1d'),
                    norm_feats=True,
                    vote_loss=dict(
                        type='ChamferDistance',
                        mode='l1',
                        reduction='none',
                        loss_dst_weight=10.0)),
                vote_aggregation_cfg=dict(
                    type='PointSAModule',
                    num_point=256,
                    radius=0.3,
                    num_sample=16,
                    mlp_channels=[256, 128, 128, 128],
                    use_xyz=True,
                    normalize_xyz=True)),
            img=dict(
                vote_module_cfg=dict(
                    in_channels=256,
                    vote_per_seed=1,
                    gt_per_seed=3,
                    conv_channels=(256, 256),
                    conv_cfg=dict(type='Conv1d'),
                    norm_cfg=dict(type='BN1d'),
                    norm_feats=True,
                    vote_loss=dict(
                        type='ChamferDistance',
                        mode='l1',
                        reduction='none',
                        loss_dst_weight=10.0)),
                vote_aggregation_cfg=dict(
                    type='PointSAModule',
                    num_point=256,
                    radius=0.3,
                    num_sample=16,
                    mlp_channels=[256, 128, 128, 128],
                    use_xyz=True,
                    normalize_xyz=True)),
            loss_weights=[0.4, 0.3, 0.3]),
        img_mlp=dict(
            in_channel=18,
            conv_channels=(256, 256),
            conv_cfg=dict(type='Conv1d'),
            norm_cfg=dict(type='BN1d'),
            act_cfg=dict(type='ReLU')),
        fusion_layer=dict(
            type='VoteFusion',
            num_classes=len(class_names),
            max_imvote_per_pixel=3),
        num_sampled_seed=1024,
        freeze_img_branch=True,
    
        # model training and testing settings
        train_cfg=dict(
            pts=dict(
                pos_distance_thr=0.3, neg_distance_thr=0.6, sample_mod='vote')),
        test_cfg=dict(
            img_rcnn=dict(score_thr=0.1),
            pts=dict(
                sample_mod='seed',
                nms_thr=0.25,
                score_thr=0.05,
                per_class_proposal=True)))
    
    train_pipeline = [
        dict(
            type='LoadPointsFromFile',
            coord_type='LIDAR',
            shift_height=True,
            load_dim=4,
            use_dim=[0, 1, 2]),
        dict(type='LoadImageFromFile'),
        dict(type='LoadAnnotations3D'),
        dict(type='LoadAnnotations', with_bbox=True),
        dict(type='Resize', img_scale=(1333, 600), keep_ratio=True),
        dict(type='RandomFlip', flip_ratio=0.0),
        dict(type='Normalize', **img_norm_cfg),
        dict(type='Pad', size_divisor=32),
        dict(
            type='RandomFlip3D',
            sync_2d=False,
            flip_ratio_bev_horizontal=0.5,
        ),
        dict(
            type='GlobalRotScaleTrans',
            rot_range=[-0.523599, 0.523599],
            scale_ratio_range=[0.85, 1.15],
            shift_height=True),
        dict(type='IndoorPointSample', num_points=20000),
        dict(type='DefaultFormatBundle3D', class_names=class_names),
        dict(
            type='Collect3D',
            keys=[
                'img', 'gt_bboxes', 'gt_labels', 'points', 'gt_bboxes_3d',
                'gt_labels_3d', 'calib'
            ])
    ]
    
    test_pipeline = [
        dict(type='LoadImageFromFile'),
        dict(
            type='LoadPointsFromFile',
            coord_type='LIDAR',
            shift_height=True,
            load_dim=4,
            use_dim=[0, 1, 2]),
        dict(
            type='MultiScaleFlipAug3D',
            img_scale=(1333, 600),
            pts_scale_ratio=1,
            flip=False,
            transforms=[
                dict(type='Resize', keep_ratio=True),
                dict(type='RandomFlip', flip_ratio=0.0),
                dict(type='Normalize', **img_norm_cfg),
                dict(type='Pad', size_divisor=32),
                dict(
                    type='GlobalRotScaleTrans',
                    rot_range=[0, 0],
                    scale_ratio_range=[1., 1.],
                    translation_std=[0, 0, 0]),
                dict(
                    type='RandomFlip3D',
                    sync_2d=False,
                    flip_ratio_bev_horizontal=0.5,
                ),
                dict(type='IndoorPointSample', num_points=20000),
                dict(
                    type='DefaultFormatBundle3D',
                    class_names=class_names,
                    with_label=False),
                dict(type='Collect3D', keys=['img', 'points', 'calib'])
    
            ]),
    ]
    # construct a pipeline for data and gt loading in show function
    # please keep its loading function consistent with test_pipeline (e.g. client)
    eval_pipeline = [
        dict(type='LoadImageFromFile'),
        dict(
            type='LoadPointsFromFile',
            coord_type='LIDAR',
            shift_height=False,
            load_dim=4,
            use_dim=[0, 1, 2]),
        dict(
            type='DefaultFormatBundle3D',
            class_names=class_names,
            with_label=False),
        dict(type='Collect3D', keys=['img', 'points', 'calib'])
    
    ]
    
    data = dict(
        samples_per_gpu=2,
        workers_per_gpu=2,
        train=dict(
            type='RepeatDataset',
            times=2,
            dataset=dict(
                type=dataset_type,
                data_root=data_root,
                ann_file=data_root + 'kitti_infos_train.pkl',
                split='training',
                pts_prefix='velodyne_reduced',
                pipeline=train_pipeline,
                modality=input_modality,
                classes=class_names,
                test_mode=False,
                box_type_3d='LiDAR')),
        val=dict(
            type=dataset_type,
            data_root=data_root,
            ann_file=data_root + 'kitti_infos_val.pkl',
            split='training',
            pts_prefix='velodyne_reduced',
            pipeline=test_pipeline,
            modality=input_modality,
            classes=class_names,
            test_mode=True,
            box_type_3d='LiDAR'),
        test=dict(
            type=dataset_type,
            data_root=data_root,
            ann_file=data_root + 'kitti_infos_val.pkl',
            split='training',
            pts_prefix='velodyne_reduced',
            pipeline=test_pipeline,
            modality=input_modality,
            classes=class_names,
            test_mode=True,
            box_type_3d='LiDAR'))
    
    evaluation = dict(pipeline=eval_pipeline,
                      interval=12)
    
    # may also use your own pre-trained image branch
    # load_from = 'https://download.openmmlab.com/mmdetection3d/v0.1.0_models/imvotenet/imvotenet_faster_rcnn_r50_fpn_2x4_sunrgbd-3d-10class/imvotenet_faster_rcnn_r50_fpn_2x4_sunrgbd-3d-10class_20210323_173222-cad62aeb.pth'  # noqa





the error is:

    2021-05-12 12:41:43,646 - mmdet - INFO - Start running, host: caizhengyi@csgpu1, work_dir: 
    /mnt/2TB1/caizhengyi/code/mmdetection3d/work_dirs/imvotenet_stage2_16x2_kitti-3d-3class
    2021-05-12 12:41:43,646 - mmdet - INFO - workflow: [('train', 1)], max: 36 epochs
    Traceback (most recent call last):
      File "/home/caizhengyi/2TB1/code/mmdetection3d/tools/train.py", line 212, in <module>
        main()
      File "/home/caizhengyi/2TB1/code/mmdetection3d/tools/train.py", line 208, in main
        meta=meta)
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
        runner.run(data_loaders, cfg.workflow)
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
        epoch_runner(data_loaders[i], **kwargs)
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
        for i, data_batch in enumerate(self.data_loader):
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
        data = self._next_data()
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
        return self._process_data(data)
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
        data.reraise()
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
        raise self.exc_type(msg)
    KeyError: Caught KeyError in DataLoader worker process 0.
    Original Traceback (most recent call last):
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
        data = fetcher.fetch(index)
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
        data = [self.dataset[idx] for idx in possibly_batched_index]
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
        data = [self.dataset[idx] for idx in possibly_batched_index]
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/dataset_wrappers.py", line 151, in __getitem__
        return self.dataset[idx % self._ori_len]
      File "/home/caizhengyi/2TB1/code/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 378, in __getitem__
        data = self.prepare_train_data(idx)
      File "/home/caizhengyi/2TB1/code/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 153, in prepare_train_data
        example = self.pipeline(input_dict)
      File "/usr/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
        data = t(data)
      File "/home/caizhengyi/2TB1/code/mmdetection3d/mmdet3d/datasets/pipelines/formating.py", line 166, in __call__
        data[key] = results[key]
    KeyError: 'calib'



how can i solve it?
